set default-list
set dotenv-load

wd := justfile_dir()
chrome := env("CHROME_BIN", "chrome")

# Build site
build: && cv
    zola build

# Check links
check:
    zola check

# Render cv to pdf with headless Chrome
cv:
    {{chrome}} --headless=new --print-to-pdf="{{wd}}/public/cv.pdf" --no-pdf-header-footer "{{wd}}/public/cv/index.html"
    rm -rf public/cv/

# Run live serve
dev:
	zola serve --open

# Download bibliographic data
download:
    Rscript download-data.R
    @echo "Success! Downloaded Zotero collections and serialized to JSON."

# Clear public directory generated by Zola
reset:
    rm -rf public
